exercism/vimscript

- .github/ISSUE_TEMPLATE.md
I forgot to delete the exercism/request-new-language-track issue
template as part of the script that bootstraps new repositories.
This is fixed in the upstream script, so it shouldn't happen again
for new language tracks.
> Delete bootstrapping artifact

- config.json
- exercises/atbash-cipher/atbash_cipher.vader
- exercises/atbash-cipher/atbash_cipher.vim
- exercises/atbash-cipher/example.vim
https://github.com/exercism/x-common/blob/bb4f220f5cef774ba05c16142a46844b2b390ead/exercises/atbash-cipher/canonical-data.json
🐹
> Add exercise: atbash-cipher

- config.json
- exercises/roman-numerals/example.vim
- exercises/roman-numerals/roman_numerals.vader
- exercises/roman-numerals/roman_numerals.vim
https://github.com/exercism/x-common/blob/070e8d5aef4cd949305d0d8289ab4b0bae4c7295/exercises/roman-numerals/canonical-data.json
> Add exercise: roman-numerals

- .vintrc.yaml
- config.json
- lib/generate.vim
This is a simple generator script.
It fetches the canonical data for an exercise from the web and converts it to a Vader file. It simply prints to stdout, so it can be piped to wherever it's needed.
It's quite hacky but worked for my local tests. I expect it to fail in some cases when the values of Ruby arrays/hashes aren't properly converted to their Vim equivalents.
But there's no need to make it perfect right now. Let's improve it incrementally. Whenever someone adds a new exercise, this script should be used for bootstrapping. If something goes wrong, it should be fixed.
> Add lib/generate.vim

- README.md
This fixes the travis build status badge.
I didn't update the gitter chat room reference, as that will probably need a manual change in gitter.
> Fix references to old repo name

- config/exercise_readme.go.tmpl
- exercises/allergies/README.md
- exercises/anagram/README.md
- exercises/atbash-cipher/README.md
- exercises/beer-song/README.md
- exercises/bob/README.md
- exercises/difference-of-squares/README.md
- exercises/etl/README.md
- exercises/hamming/README.md
- exercises/hello-world/README.md
- exercises/largest-series-product/README.md
- exercises/leap/README.md
- exercises/nucleotide-count/README.md
- exercises/pangram/README.md
- exercises/phone-number/README.md
- exercises/raindrops/README.md
- exercises/rna-transcription/README.md
- exercises/roman-numerals/README.md
- exercises/scrabble-score/README.md
- exercises/triangle/README.md
- exercises/word-count/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
> Generate static exercise README templates

- exercises/anagram/README.md
- exercises/anagram/anagram.vim
Instead of splitting the conditions between the instructions and the code, better to keep them both in the same place. I have a practical situation where a student hadn''t noticed the additional constraints and was wondering why their tests were failing. I think this would help.
I could also keep them in both, but I feel like a "Hints:" section in the comments would be redundant.
> Move conditions from code comment to the instructions

- exercises/leap/example.vim
- exercises/leap/leap.vim
The argument name `year` is better than `number` or `num` here.
> Improve argument name in "leap" exercise

- exercises/practice/allergies/.meta/config.json
- exercises/practice/anagram/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/beer-song/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …
> 🤖 Sync exercise files keys based on file path patterns

- exercises/practice/allergies/.meta/config.json
- exercises/practice/anagram/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/beer-song/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
Each Concept and Practice Exercise will have to define a _blurb_, which is a short description of the exercise.
The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:
Blurbs must be limited to 350 chars and will be truncated in some views.
For Practice Exercises that are based on an exercise defined in the problem-specification repo, the blurb must match the contents of the problem-specifications exercises, which is defined in its `metadata.yml` file. In this PR, we'll do an initial syncing of the blurb. The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.
If the Practice Exercise was _not_ based on a problems-specifications exercise, we've used the blurb from its …
> 🤖 Add blurb to .meta/config.json files

- README.md
- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- exercises/practice/allergies/.meta/tests.toml
- exercises/practice/anagram/.meta/tests.toml
- exercises/practice/atbash-cipher/.meta/tests.toml
- exercises/practice/beer-song/.meta/tests.toml
- exercises/practice/bob/.meta/tests.toml
- exercises/practice/difference-of-squares/.meta/tests.toml
- exercises/practice/etl/.meta/tests.toml
- exercises/practice/hamming/.meta/tests.toml
- exercises/practice/hello-world/.meta/tests.toml
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/leap/.meta/tests.toml
- exercises/practice/nucleotide-count/.meta/tests.toml
- exercises/practice/pangram/.meta/tests.toml
- exercises/practice/phone-number/.meta/tests.toml
- exercises/practice/raindrops/.meta/tests.toml
- exercises/practice/rna-transcription/.meta/tests.toml
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/scrabble-score/.meta/tests.toml
- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/word-count/.meta/tests.toml
We're in the process of re-opening the [Problem Specifications repo](https://github.com/exercism/problem-specifications), as discussed in [this issue](https://github.com/exercism/problem-specifications/issues/1674).
This PR adds `.meta/tests.toml` files for all exercises for which canonical data is defined in the Problem Specifications repo.
We'll now discuss _why_ we're making this change.
While most of the changes to the Problem Specifications repo are specific to that repo, there is one track-specific change:
> If a track implements an exercise for which test data exists, the exercise _must_ contain a `.meta/tests.toml` file.
The goal of the `tests.toml` file is to keep track of which tests are implemented by the exercise.
Tests in this file are identified by their UUID and each test …
> Bringing your track in line with the latest changes to Problem Specifications

- exercises/practice/allergies/.meta/config.json
- exercises/practice/anagram/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/beer-song/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_
---
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).
Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.
These are the things you, the maintainers, should do:
**For clarity, authors should …
> 🤖 Add authors and contributors to Practice Exercises

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/largest_series_product.vader
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications

- config.json
May or may not need some massaging.  Pulled from various resources and articles.  Including [vim9.txt](https://vimhelp.org/vim9.txt.html), [Softpanorama](https://softpanorama.org/Editors/Vimorama/vim_scripting.shtml), and [Effective VimScript](https://www.arp242.net/effective-vimscript.html), as well as [8thlight](https://8thlight.com/insights/a-case-study-in-vim-script-101-making-a-test-runner).
1.  **Extensible:** _Looking for certain functionality?  It can be easily created and deployed._
2. **Deep Vim Integration:** _Productivity win! Access and manipulate Vim internal data structures and settings with ease._
3. **Expressive syntax:** _Do a lot with a little. Write compact scripts that are highly readable._
4. **Multi-paradigm:** _Supports writing imperatively or functionally._
5. …
> [Track]: Added First Pass at Key Features and Icons.

- config.json
Example implementations for the CI are within the .meta subfolder, not the root of the exercise.
> Update files -> example file path

- config.json
I sorted the exercises by the current difficulty and then name. I made an exemption for `resistor-color-duo` and placed it after `resistor-color` to suggest that `resistor-color` naturally leads into `resistor-color-duo`. I saw this discussed on another track, and I liked the approach.
> Sort practice exercises by difficulty and name

- config.json
The repo README and track docs all use 'Vim script' not 'Vimscript' unless it's a link to an external resource like https://learnvimscriptthehardway.stevelosh.com/.
> Vimscript to Vim script in track blurb

- config.json
- exercises/practice/flatten-array/.docs/instructions.md
- exercises/practice/flatten-array/.meta/config.json
- exercises/practice/flatten-array/.meta/example.vim
- exercises/practice/flatten-array/.meta/tests.toml
- exercises/practice/flatten-array/flatten_array.vader
- exercises/practice/flatten-array/flatten_array.vim
> Add flatten-array exercise

- .github/workflows/ci-vint.yml
- .github/workflows/ci.yml
This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.
> CI: pin GitHub Actions runners

- config.json
- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/space-age/.meta/config.json
- exercises/practice/space-age/.meta/example.vim
- exercises/practice/space-age/.meta/tests.toml
- exercises/practice/space-age/space_age.vader
- exercises/practice/space-age/space_age.vim
Related to #172.
I removed the usual examples from the function documentation since I didn't want to bias a student towards rounding to two digits or not.
Also, the Before block is awkward, but I couldn't define the predicate outside of it. The other option I saw was an Execute block, but that'll make the definition be seen as another test that passes every time (no assert). That's not a great solution.
> Add space-age

- config.json
https://github.com/exercism/problem-specifications/blob/main/exercises/beer-song/.deprecated notes this exercise is deprecated. `bottle-song` is the replacement
> Deprecate beer-song in track config

- .github/workflows/ci-vint.yml
- .github/workflows/ci.yml
This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.
> CI: pin GitHub Actions workflows

- config.json
I noticed darts was out of order on the website. Looking over the config, grains should come before hello-world, not high-scores.
> Resort exercises

- config.json
- exercises/practice/run-length-encoding/.docs/instructions.md
- exercises/practice/run-length-encoding/.meta/config.json
- exercises/practice/run-length-encoding/.meta/example.vim
- exercises/practice/run-length-encoding/run_length_encoding.vader
- exercises/practice/run-length-encoding/run_length_encoding.vim
~~This is currently draft/unfinished/work-in-progress.~~
Ready for review.
@BNAndras
> Exercise: Run-length encoding (and decoding)

- exercises/practice/list-ops/list_ops.vim
A confusing situation for the student.
> list-ops: stub file has functions with args in the wrong order

- exercises/practice/isogram/.meta/example.vim
Lowercase a is 97 and lowercase Z is 122 per https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin_script
> Fix incorrect codepoint boundaries in isogram example

- exercises/practice/armstrong-numbers/.meta/tests.toml
`configlet` is warning that "false" needs to be false.
> Remove invalid quotes from tests.toml for armstrong-numbers

- exercises/practice/two-fer/.meta/tests.toml
Should be merged as [no important files changed] since all three tests are accounted for.
> Add two-fer tests.toml

- exercises/practice/pangram/.meta/tests.toml
- exercises/practice/pangram/pangram.vader
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/roman_numerals.vader
- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/triangle/triangle.vader
> Update tests for pangram, roman-numerals, and triangle

- .github/workflows/ci.yml
Once exercism/vimscript-test-runner#28 is merged, we can update the CI to support Vim 9. I opted to build Vim from source rather than use a PPA. This can work until the Ubuntu runner has a more modern Vim package available. Another approach would be to use our test runner image to test each exercise in isolation, which will require a little more research.
> Update CI to Vim 9

- exercises/practice/transpose/.meta/example.vim
- exercises/practice/transpose/transpose.vader
- exercises/practice/transpose/transpose.vim
The tests for transpose were using single quotes around \n, with the result that the two-character sequence backslash+n was being used instead of newlines to join lines together.  Solutions had to accept input in this unusual format and return the result in the same style.  This change switches to double quotes, so that newlines are used as expected.  Also clean up a garbled comment in the stub code.
This was discussed in the forum: https://forum.exercism.org/t/wrong-line-joins-in-transpose/9005
> Use double quotes so that newlines are handled properly.

- config.json
Until #256 is resolved, I'd propose we not show grains on the track. `status: "wip"` will set it so only maintainers can see the exercise on the Exercism website. When grains is fixed, we can remove that added line and the exercise will go back to active status by default.
> Set grains to WIP

- config.json
Vim script doesn't seem to natively support parallel code execution unless I'm missing something obvious.
> Forego parallel-letter-frequency

- exercises/practice/phone-number/phone_number.vader
The missing tests here seem to be input validation ones. The implementation expects an empty string to be returned instead of an error thrown so nothing significant changed here I believe.
> Sync phone number tests

- .github/workflows/test.yml
I'm bumping the CI to Ubuntu 24.04, but we're using the test runner image to do the actual exercise testing so this shouldn't be a major deal.
> Bump CI to Ubuntu 24.04

- exercises/practice/roman-numerals/.meta/tests.toml
Test was added in #295 but I didn't update the toml file at the time.
> Sync tests toml for roman-numerals

- config.json
- exercises/practice/grade-school/.docs/instructions.md
- exercises/practice/grade-school/.meta/config.json
- exercises/practice/grade-school/.meta/example.vim
- exercises/practice/grade-school/.meta/tests.toml
- exercises/practice/grade-school/grade_school.vader
- exercises/practice/grade-school/grade_school.vim
For #48in24, using the tests from https://github.com/exercism/coffeescript/pull/327
> Add grade-school

- config.json
- exercises/practice/grains/.docs/instructions.append.md
- exercises/practice/grains/.meta/config.json
- exercises/practice/grains/.meta/example.vim
- exercises/practice/grains/grains.vader
- exercises/practice/grains/grains.vim
To work around Vimscripts 2^63 limit for integers, the tests have been created to expect the integral values as strings.
Following #322
> grains exercise: test against integer values as strings.

- exercises/practice/grains/.docs/instructions.append.md
> Typo: "ov" => "of'

- exercises/practice/anagram/.docs/instructions.md
- exercises/practice/anagram/.meta/tests.toml
- exercises/practice/anagram/anagram.vader
- exercises/practice/bob/.meta/tests.toml
- exercises/practice/bob/bob.vader
- exercises/practice/custom-set/.meta/tests.toml
- exercises/practice/custom-set/custom_set.vader
- exercises/practice/flatten-array/.docs/instructions.md
- exercises/practice/flatten-array/.docs/introduction.md
- exercises/practice/flatten-array/.meta/tests.toml
- exercises/practice/flatten-array/flatten_array.vader
- exercises/practice/grains/.docs/instructions.md
- exercises/practice/grains/.docs/introduction.md
- exercises/practice/grains/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/pig-latin/.meta/tests.toml
- exercises/practice/pig-latin/pig_latin.vader
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/protein_translation.vader
- exercises/practice/reverse-string/.meta/tests.toml
- exercises/practice/reverse-string/reverse_string.vader
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/sieve/.docs/instructions.md
- exercises/practice/word-count/.meta/example.vim
- exercises/practice/word-count/.meta/tests.toml
- exercises/practice/word-count/word_count.vader
Configlet shows unsynced tests for `anagram`, `bob`, `custom-set`, `pig-latin`, `protein-translation`, `reverse-string`, and `word-count`. This PR once ready should sync as many of these as possible.
> Sync problem-specifications tests

- config.json
- exercises/practice/change/.docs/instructions.md
- exercises/practice/change/.docs/introduction.md
- exercises/practice/change/.meta/config.json
- exercises/practice/change/.meta/example.vim
- exercises/practice/change/.meta/tests.toml
- exercises/practice/change/change.vader
- exercises/practice/change/change.vim
https://forum.exercism.org/t/adding-change-exercise/17766
> Add `change`
