config.json, exercises/hello-world/example.vim, exercises/hello-world/hello_world.vader, exercises/hello-world/hello_world.vim
This PR adds the problem (`hello_world.vim`), its test file (`hello_world.vader`), and an example solution (`example.vim`).
=> [RFC] Add problem: hello-world

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
=> Add documentation

.travis.yml, bin/ci
- Run all tests using [vader.vim](https://github.com/junegunn/vader.vim).
- Check all Vimscript files for best practices using the linter [vint](https://github.com/Kuniwak/vint).
=> [RFC] Set up CI

config.json, exercises/leap/example.vim, exercises/leap/leap.vader, exercises/leap/leap.vim
The tests are copied 1:1 from the Ruby track.
=> Add exercise: leap

config.json, exercises/rna-transcription/example.vim, exercises/rna-transcription/rna_transcription.vader, exercises/rna-transcription/rna_transcription.vim
https://github.com/exercism/x-common/blob/master/exercises/rna-transcription/canonical-data.json
=> Add exercise: rna-transcription

config.json, exercises/anagram/anagram.vader, exercises/anagram/anagram.vim, exercises/anagram/example.vim
https://github.com/exercism/x-common/blob/master/exercises/anagram/canonical-data.json
=> Add exercise: anagram

config.json, exercises/difference-of-squares/difference_of_squares.vader, exercises/difference-of-squares/difference_of_squares.vim, exercises/difference-of-squares/example.vim
Tests coincide with:
https://github.com/exercism/x-common/blob/1bd8529776f97780a3b201aa3ee27926118b2efd/exercises/difference-of-squares/canonical-data.json
Additional tests for input == 0.
🐶
=> Add exercise: difference-of-squares

config.json, exercises/raindrops/example.vim, exercises/raindrops/raindrops.vader, exercises/raindrops/raindrops.vim
https://github.com/exercism/x-common/blob/1bd8529776f97780a3b201aa3ee27926118b2efd/exercises/raindrops/canonical-data.json
🐱
=> Add exercise: raindrops

config.json, exercises/word-count/example.vim, exercises/word-count/word_count.vader, exercises/word-count/word_count.vim
Tests coincide with:
https://github.com/exercism/x-common/blob/cd26d49d1fb139e38b6c74a3ea3cdf3bf5a311df/exercises/word-count/canonical-data.json
🐭
=> Add exercise: word-count

config.json
Let's get this party started! 🎉
---
Is anything speaking against submitting my own solutions, so that the first users of the track have solutions to compare against?
=> Config: toggle "active"

config.json, exercises/nucleotide-count/example.vim, exercises/nucleotide-count/nucleotide_count.vader, exercises/nucleotide-count/nucleotide_count.vim
=> Add exercise: nucleotide-count

docs/ABOUT.md
Change "at" to "are" and add hint of acting on objects.
=> "at" to "are" change and clarification

.travis.yml
My poor inbox is full enough already. :-)
(Mails are still sent on failure.)
=> CI: don't send mail on success

docs/LEARNING.md
Fix a broken link to resources page
=> docs/LEARNING: fix link to resources page

exercises/anagram/anagram.vim
The function name and order of arguments are wrong.
=> anagram: fix example comment

config/maintainers.json
I'm not using exercism myself anymore and even though this repo is pretty
low-traffic, I don't have enough time to spend on it and keeping up with all the
changes in the exercism org.
Thanks!
=> Config: remove me as a maintainer

exercises/practice/hello-world/hello_world.vim
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

config.json
This should let the configlet pass linting though.  And leaves space for
the future for an exemplar solution per exercise.
=> Exemplar files do not exist yet.

config.json
=> Set online_editor.indent_size to 2

exercises/practice/allergies/.meta/config.json, exercises/practice/anagram/.meta/config.json, exercises/practice/atbash-cipher/.meta/config.json, exercises/practice/beer-song/.meta/config.json, exercises/practice/bob/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/etl/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/largest-series-product/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/nucleotide-count/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/phone-number/.meta/config.json, exercises/practice/raindrops/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/roman-numerals/.meta/config.json, exercises/practice/scrabble-score/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/word-count/.meta/config.json
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.
=> Reformat exercise config files

config.json, exercises/practice/two-fer/.docs/instructions.md, exercises/practice/two-fer/.docs/introduction.md, exercises/practice/two-fer/.meta/config.json, exercises/practice/two-fer/.meta/example.vim, exercises/practice/two-fer/two_fer.vader, exercises/practice/two-fer/two_fer.vim
=> Add two-fer

config.json, exercises/practice/resistor-color-duo/.docs/instructions.md, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color-duo/.meta/example.vim, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/resistor_color_duo.vader, exercises/practice/resistor-color-duo/resistor_color_duo.vim
=> Add resistor-color-duo

config.json, exercises/practice/resistor-color/.docs/instructions.md, exercises/practice/resistor-color/.meta/config.json, exercises/practice/resistor-color/.meta/example.vim, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/resistor-color/resistor_color.vader, exercises/practice/resistor-color/resistor_color.vim
=> Add resistor-color

config.json
As of 4.0.0-beta.16, `configlet fmt` now operates on the track-level config.json file.
=> Format track config.json

config.json
=> Sort exercises by binned difficulty

config.json, exercises/practice/all-your-base/.docs/instructions.md, exercises/practice/all-your-base/.meta/config.json, exercises/practice/all-your-base/.meta/example.vim, exercises/practice/all-your-base/.meta/tests.toml, exercises/practice/all-your-base/all_your_base.vader, exercises/practice/all-your-base/all_your_base.vim
=> Add all-your-base exercise

config.json, exercises/practice/isogram/.docs/instructions.md, exercises/practice/isogram/.meta/config.json, exercises/practice/isogram/.meta/example.vim, exercises/practice/isogram/.meta/tests.toml, exercises/practice/isogram/isogram.vader, exercises/practice/isogram/isogram.vim
=> Add isogram exercise

config.json, exercises/practice/perfect-numbers/.docs/instructions.md, exercises/practice/perfect-numbers/.meta/config.json, exercises/practice/perfect-numbers/.meta/example.vim, exercises/practice/perfect-numbers/.meta/tests.toml, exercises/practice/perfect-numbers/perfect_numbers.vader, exercises/practice/perfect-numbers/perfect_numbers.vim
=> Add perfect-numbers

config.json, exercises/practice/reverse-string/.docs/instructions.md, exercises/practice/reverse-string/.meta/config.json, exercises/practice/reverse-string/.meta/example.vim, exercises/practice/reverse-string/.meta/tests.toml, exercises/practice/reverse-string/reverse_string.vader, exercises/practice/reverse-string/reverse_string.vim
=> Add reverse-string

config.json, exercises/practice/collatz-conjecture/.docs/instructions.md, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/collatz-conjecture/.meta/example.vim, exercises/practice/collatz-conjecture/.meta/tests.toml, exercises/practice/collatz-conjecture/collatz_conjecture.vader, exercises/practice/collatz-conjecture/collatz_conjecture.vim
Related to #172. 
During this, I noticed the test suite generator added tests that were marked as not to be included.
=> Add collatz-conjecture

config.json, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/binary-search/.docs/introduction.md, exercises/practice/binary-search/.meta/config.json, exercises/practice/binary-search/.meta/example.vim, exercises/practice/binary-search/.meta/tests.toml, exercises/practice/binary-search/binary_search.vader, exercises/practice/binary-search/binary_search.vim
Related to #172. Only tweak to the test suite was changing every mention of array to list.
=> Add binary-search

config.json, exercises/practice/secret-handshake/.docs/instructions.md, exercises/practice/secret-handshake/.docs/introduction.md, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/secret-handshake/.meta/example.vim, exercises/practice/secret-handshake/.meta/tests.toml, exercises/practice/secret-handshake/secret_handshake.vader, exercises/practice/secret-handshake/secret_handshake.vim
=> Add secret-handshake

config.json, exercises/practice/high-scores/.docs/instructions.md, exercises/practice/high-scores/.meta/config.json, exercises/practice/high-scores/.meta/example.vim, exercises/practice/high-scores/.meta/tests.toml, exercises/practice/high-scores/high_scores.vader, exercises/practice/high-scores/high_scores.vim
=> Add high-scores

config.json, exercises/practice/armstrong-numbers/.docs/instructions.md, exercises/practice/armstrong-numbers/.meta/config.json, exercises/practice/armstrong-numbers/.meta/example.vim, exercises/practice/armstrong-numbers/.meta/tests.toml, exercises/practice/armstrong-numbers/armstrong_numbers.vader, exercises/practice/armstrong-numbers/armstrong_numbers.vim
=> Add armstrong-numbers

config.json, exercises/practice/strain/.docs/instructions.md, exercises/practice/strain/.meta/config.json, exercises/practice/strain/.meta/example.vim, exercises/practice/strain/.meta/tests.toml, exercises/practice/strain/strain.vader, exercises/practice/strain/strain.vim
=> Add strain exercise

config.json, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.meta/config.json, exercises/practice/grains/.meta/example.vim, exercises/practice/grains/.meta/tests.toml, exercises/practice/grains/grains.vader, exercises/practice/grains/grains.vim
=> Add grains exercise

config.json, exercises/practice/robot-simulator/.docs/instructions.md, exercises/practice/robot-simulator/.meta/config.json, exercises/practice/robot-simulator/.meta/example.vim, exercises/practice/robot-simulator/.meta/tests.toml, exercises/practice/robot-simulator/robot_simulator.vader, exercises/practice/robot-simulator/robot_simulator.vim
=> Add robot-simulator

config.json, exercises/practice/micro-blog/.docs/instructions.md, exercises/practice/micro-blog/.meta/config.json, exercises/practice/micro-blog/.meta/example.vim, exercises/practice/micro-blog/.meta/tests.toml, exercises/practice/micro-blog/micro_blog.vader, exercises/practice/micro-blog/micro_blog.vim
=> Add micro-blog exercise

config.json, exercises/practice/proverb/.docs/instructions.md, exercises/practice/proverb/.meta/config.json, exercises/practice/proverb/.meta/example.vim, exercises/practice/proverb/.meta/tests.toml, exercises/practice/proverb/proverb.vader, exercises/practice/proverb/proverb.vim
=> Add proverb exercise

config.json, exercises/practice/custom-set/.docs/instructions.md, exercises/practice/custom-set/.meta/config.json, exercises/practice/custom-set/.meta/example.vim, exercises/practice/custom-set/.meta/tests.toml, exercises/practice/custom-set/custom_set.vader, exercises/practice/custom-set/custom_set.vim
=> Add custom-set

config.json, exercises/practice/rotational-cipher/.docs/instructions.md, exercises/practice/rotational-cipher/.meta/config.json, exercises/practice/rotational-cipher/.meta/example.vim, exercises/practice/rotational-cipher/.meta/tests.toml, exercises/practice/rotational-cipher/rotational_cipher.vader, exercises/practice/rotational-cipher/rotational_cipher.vim
=> Add rotational-cipher

config.json, exercises/practice/series/.docs/instructions.md, exercises/practice/series/.meta/config.json, exercises/practice/series/.meta/example.vim, exercises/practice/series/.meta/tests.toml, exercises/practice/series/series.vader, exercises/practice/series/series.vim
=> Add series exercise

config.json, exercises/practice/list-ops/.docs/instructions.md, exercises/practice/list-ops/.meta/config.json, exercises/practice/list-ops/.meta/example.vim, exercises/practice/list-ops/.meta/tests.toml, exercises/practice/list-ops/list_ops.vader, exercises/practice/list-ops/list_ops.vim
Related to #172.
I have two bugs in my foldl/foldr implementation to resolve
=> Add list-ops

config.json, exercises/practice/matrix/.docs/instructions.md, exercises/practice/matrix/.meta/config.json, exercises/practice/matrix/.meta/example.vim, exercises/practice/matrix/.meta/tests.toml, exercises/practice/matrix/matrix.vader, exercises/practice/matrix/matrix.vim
Related to #172.
Any feelings about the string to number conversion? I don't feel like it adds much to the exercise so we could make the expected values be lists of stringified numbers instead. Then the students can focus on manipulating the 2D array.
=> Add matrix exercise

exercises/practice/etl/etl.vim
For the merge comment, `[no important changes]` would be appropriate here: http://forum.exercism.org/t/maintainers-new-no-important-files-changed-flag-added/6500
=> ETL exercise: provide hint to student to lowercase the letters

config.json, exercises/practice/two-bucket/.docs/instructions.md, exercises/practice/two-bucket/.meta/config.json, exercises/practice/two-bucket/.meta/example.vim, exercises/practice/two-bucket/.meta/tests.toml, exercises/practice/two-bucket/two_bucket.vader, exercises/practice/two-bucket/two_bucket.vim
I gave this difficulty 6, higher than any other exercise. Consequently, the stub is very empty.
=> Add two-bucket exercise

config.json, exercises/practice/transpose/.docs/instructions.md, exercises/practice/transpose/.meta/config.json, exercises/practice/transpose/.meta/example.vim, exercises/practice/transpose/.meta/tests.toml, exercises/practice/transpose/transpose.vader, exercises/practice/transpose/transpose.vim
=> Add transpose

exercises/practice/bob/bob.vader
No new tests here. I did notice some of the expected inputs didn't line up exactly with the canonical data so I went ahead and used the test generator.
=> Sync bob tests

exercises/practice/difference-of-squares/difference_of_squares.vader
Minor reformatting. No tests added so we'll merge as no important files changed.
=> Format difference-of-squares test suite

exercises/practice/hamming/.meta/example.vim, exercises/practice/hamming/hamming.vader, exercises/practice/hamming/hamming.vim
Only tests changed here were reimplements for the expected error message
=> Sync hamming tests

exercises/practice/leap/leap.vader
=> Sync leap tests

config.json, exercises/practice/spiral-matrix/.docs/instructions.md, exercises/practice/spiral-matrix/.docs/introduction.md, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/spiral-matrix/.meta/example.vim, exercises/practice/spiral-matrix/.meta/tests.toml, exercises/practice/spiral-matrix/spiral_matrix.vader, exercises/practice/spiral-matrix/spiral_matrix.vim
=> Add spiral matrix

config.json, exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/matching-brackets/.docs/introduction.md, exercises/practice/matching-brackets/.meta/config.json, exercises/practice/matching-brackets/.meta/example.vim, exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/matching_brackets.vader, exercises/practice/matching-brackets/matching_brackets.vim
=> Add matching-brackets

config.json, exercises/practice/pascals-triangle/.docs/instructions.md, exercises/practice/pascals-triangle/.docs/introduction.md, exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/pascals-triangle/.meta/example.vim, exercises/practice/pascals-triangle/.meta/tests.toml, exercises/practice/pascals-triangle/pascals_triangle.vader, exercises/practice/pascals-triangle/pascals_triangle.vim
=> Add pascals-triangle

config.json, exercises/practice/kindergarten-garden/.docs/instructions.md, exercises/practice/kindergarten-garden/.docs/introduction.md, exercises/practice/kindergarten-garden/.meta/config.json, exercises/practice/kindergarten-garden/.meta/example.vim, exercises/practice/kindergarten-garden/.meta/tests.toml, exercises/practice/kindergarten-garden/kindergarten_garden.vader, exercises/practice/kindergarten-garden/kindergarten_garden.vim
=> Add kindergarten-garden

config.json, exercises/practice/food-chain/.docs/instructions.md, exercises/practice/food-chain/.meta/config.json, exercises/practice/food-chain/.meta/example.vim, exercises/practice/food-chain/.meta/tests.toml, exercises/practice/food-chain/food_chain.vader, exercises/practice/food-chain/food_chain.vim
This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-10-29-food-chain/12899).
=> Add food-chain exercise
